name:                Hygeia
version:             0.1.0.0
github:              "githubuser/Hygeia"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Hygeia#readme>

default-extensions:
- RankNTypes
- ScopedTypeVariables
- DataKinds
- PolyKinds
- ExistentialQuantification
- MultiParamTypeClasses
- TypeFamilies
- TypeOperators
- TypeApplications
- GADTs
- OverloadedStrings


dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- parsec >= 3.1.16.0
- time
- optparse-applicative >= 0.17
- turtle
- mime-mail
- smtp-mail

library:
  source-dirs: src

executables:
  Hygeia-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hygeia

tests:
  Hygeia-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hygeia
