name:                Hygeia
version:             0.1.0.0
github:              "Ei30metry/Hygeia"
license:             BSD3
author:              "Artin Ghasivand"
maintainer:          "ghasivand.artin@gmail.com"
copyright:           "2022 Artin Ghasivand"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Hygeia#readme>

default-extensions:
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveGeneric
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- GADTs
- InstanceSigs
- KindSignatures
- NoCUSKs
- NoNamedWildCards
- NoStarIsType
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances
- GeneralizedNewtypeDeriving



dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- time
- parsec
- optparse-applicative >= 0.17
- mime-mail
- singletons
- singletons-base
- process
- unix
- mtl
- transformers
- turtle
- lens

library:
  source-dirs: src

executables:
  Hygeia-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hygeia

tests:
  Hygeia-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hygeia
    - tasty
    - hedgehog
    - tasty-hedgehog
    - tasty-golden
